#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# RHN/Spacewalk XMLRPC API script
# requires the python-rhnapi and python-progressbar modules
# requires the python-rhnapi module
#
# Copyright 2009-2012 Stuart Sears
#
# This file is part of spw-api-scripts
#
# spw-api-scripts is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# spw-api-scripts is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with spw-api-scripts. If not, see http://www.gnu.org/licenses/.

__doc__ = """
Compares a textdump of 'rpm -qa' from a system to a channel in RHN

The rpm -qa output should look like this:
NAME|VERSION|RELEASE|ARCH|EPOCH

so set your --queryformat appropriately
e.g. rpm -qa --queryformat '%{NAME}|%{VERSION}|%{RELEASE}|%{ARCH}|%{EPOCH}\n'

The separator for these fields can be specified on the commandline, if you absolutely must.
"""
__author__ = "Stuart Sears <stuart@sjsears.com>

# standard library imports
import sys
import os
from optparse import OptionParser, OptionGroup
from pprint import pprint

# custom module imports
import rhnapi
from rhnapi import packages
from rhnapi import channel
from rhnapi import utils

# from progressbar, for user feedback
from progressbar import Counter,Percentage,ProgressBar, Timer, AnimatedMarker, Bar

# configuration variables. Probably okay, actually.
RHNCONFIG = '~/.rhninfo'
RHNHOST = 'localhost'
# put these in your configfile, dammit;
RHNUSER = None
RHNPASS = None

# --------------------------------------------------------------------------------- #

def parse_cmdline(argv):
    """
    process the commandline :)
    """
    preamble = """Reads a textfile containing a dump of rpm -qa from a system with a channel in RHN Satellite.
 The rpm queryformat should contain NAME|VERSION|RELEASE|ARCH|EPOCH information.
 Separator can be any reasonable char but defaults to the pipe character. """
    usagestr = "%prog [RHNOPTS] [-f OUTPUTFILE ] [ -S SEPARATOR ] -c CHANNEL_LABEL INPUTFILE"
    parser = OptionParser(usage = usagestr, description = preamble)
    parser.add_option("--debug", action = "store_true", default = False,
            help = "enable debug output for RHN session (XMLRPC errors etc")
    parser.add_option("-v", "--verbose", action = "store_true", default = False,
            help = "enable debug output for RHN session (XMLRPC errors etc")

    # RHN Satellite options group
    rhngrp = OptionGroup(parser, "RHN Satellite Options", "Defaults can be set in your RHN API config file (%s)" % RHNCONFIG )
    rhngrp.add_option("--server",help="RHN satellite server hostname [%default]", default=RHNHOST)
    rhngrp.add_option("--login", help="RHN login (username)" , default=RHNUSER)
    rhngrp.add_option("--pass", dest = "password", help="RHN password. This is better off in a config file.", default=RHNPASS)
    rhngrp.add_option("--config", dest = "config", help="Local RHN configuration file [ %default ]", default=RHNCONFIG)
    rhngrp.add_option("--cache", action = "store_true", default = False,
        help = "save usernames and password in config file, if missing")
    parser.add_option_group(rhngrp)

    # script-specific options
    changrp = OptionGroup(parser, "Channel Options")
    changrp.add_option("-c", "--channel", help = "Channel LABEL to diff against.")
    changrp.add_option("-f", "--file", help = "output file for diffs")
    changrp.add_option("-S", "--separator", default = "|",
        help = "separator used in rpm -qa queryformat. default is '%default'")
    parser.add_option_group(changrp)

    # parse the arguments we were given (commandline, probably)
    opts, args = parser.parse_args(argv)

    # check the args for errors etc...
    if len(args) != 1:
        parser.print_help()
        sys.exit(0)
    else:
        if not os.path.isfile(args[0]):
            print "input file %s does not exist" % args[0]
            parser.print_help()
            sys.exit(1)
    # only expecting one arg, so let's just return that instead of a list            
    return opts, args[0]



# --------------------------------------------------------------------------------- #

def main():
    # there should only be one entry in args, so...
    opts, inputfile = parse_cmdline(sys.argv[1:])
    outputfile = inputfile.replace('.txt','.json')
    try:
        # initialise an RHN Session
        RHN = rhnapi.rhnSession(opts.server, opts.login, opts.password, config=opts.config, cache_creds=opts.cache, debug=opts.debug)
        # while in development:
        if opts.debug:
            RHN.enableDebug()
        filepkgs = []
        widgets = ['Packages: ', Counter(), ' Errata [', Percentage(), ']', Bar(), '(', Timer(), ')']
        pbar = ProgressBar(widgets = widgets, term_width = 80, maxval = len(open(inputfile).readlines())).start()
        counter = 0
        for line in open(inputfile):
            try:
                # lines should be name|ver|rel|arch|epoch, where epoch is mostly '(none)'
                pkgname, pkgver, pkgrel , pkgarch, pkgepoch = line.split(opts.separator)
                if pkgepoch.strip() == '(none)':
                    pkgepoch = ''
            except:
                # ignore lines not matching the pattern
                counter +=1
                pbar.update(counter)
                continue

            pkgdetails = packages.findByNvrea(RHN, pkgname, pkgver, pkgrel , pkgarch, pkgepoch)
        
            if pkgdetails:
                filepkgs.append(pkgdetails)
            counter += 1
            pbar.update(counter)

        print "dumping to %s " % outputfile
        utils.dumpJSON(filepkgs, outputfile)

    except KeyboardInterrupt:
        print "operation cancelled"
        sys.exit(1)

# --------------------------------------------------------------------------------- #

if __name__ == '__main__':
    main()
    


    
    
    
