#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# RHN/Spacewalk XMLRPC API script
# requires the python-rhnapi and python-progressbar modules
#
# Copyright 2009-2012 Stuart Sears
#
# This file is part of spw-api-scripts
#
# spw-api-scripts is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# spw-api-scripts is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with spw-api-scripts. If not, see http://www.gnu.org/licenses/.

"""
Lists all systems registered to your satellite which have packages flagged as being of 'unknown'  arch.
This is a known issue with older satellite releases and older RHEL4 systems.
"""
# standard library imports
import sys
from optparse import OptionParser, OptionGroup
from operator import itemgetter
import time

# custom module imports
import rhnapi
from rhnapi import system

# progressbar
from progressbar import Counter,Percentage,ProgressBar, Timer, AnimatedMarker, Bar


# configuration variables. Probably okay, actually.
RHNCONFIG = '~/.rhninfo'
RHNHOST = 'localhost'
# put these in your configfile, dammit;
RHNUSER = None
RHNPASS = None

# --------------------------------------------------------------------------------- #
def parse_cmdline(argv):
    """
    process the commandline :)
    """
    preamble = """Lists systems whose satellite profile has packages marked of 'unknown' architecture.
This is an artifact seen on older RHEL4 systems."""
    usagestr = "%prog [RHNOPTS]"
    # initialise our parser and set some default options
    parser = OptionParser(usage = usagestr, description = preamble)
    parser.add_option("--debug", action = "store_true", default = False,
            help = "enable debug output for RHN session (XMLRPC errors etc")
    parser.add_option('-v', '--verbose', action = 'store_true', default = False,
            help = "increase verbosity")

    # RHN Satellite options group
    rhngrp = OptionGroup(parser, "RHN Satellite Options", "Defaults can be set in your RHN API config file (%s)" % RHNCONFIG )
    rhngrp.add_option("--server",help="RHN satellite server hostname [%default]", default=RHNHOST)
    rhngrp.add_option("--login", help="RHN login (username)" , default=RHNUSER)
    rhngrp.add_option("--pass", dest = "password", help="RHN password. This is better off in a config file.", default=RHNPASS)
    rhngrp.add_option("--config", dest = "config", help="Local RHN configuration file [ %default ]", default=RHNCONFIG)
    rhngrp.add_option("--cache", action = "store_true", default = False,
        help = "save usernames and password in config file, if missing")
    parser.add_option_group(rhngrp)

    # script-specific options

    opts, args = parser.parse_args(argv)
    # check the args for errors etc...

    # finally...
    return opts, args

# --------------------------------------------------------------------------------- #

def pretty_system_list(syslist, sortkey, reverse=False):
    """
    prints a systemlist sorted by a given key
    """
    for system in sorted(syslist, key = itemgetter(sortkey), reverse = reverse):
        lcheck = time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(str(system['last_checkin']), '%Y%m%dT%H:%M:%S'))
        print "%-12d %-22s %-18s %s" %(system['id'], system['name'], lcheck, system['base_channel'])



# --------------------------------------------------------------------------------- #
if __name__ == '__main__':
    
    opts, args = parse_cmdline(sys.argv[1:])
    # initialise an RHN Session
    # safety mechanism until the script actually works:
    try:
        RHN = rhnapi.rhnSession(opts.server, opts.login, opts.password, config=opts.config, savecreds=opts.cache, debug=opts.debug)
        # more fully-featured debug info
        if opts.debug:
            RHN.enableDebug()

        systemlist = system.listSystems(RHN)
        failed_systems = []
        widgets = ['progress: ', Counter(), ' Systems [', Percentage(), ']', Bar(), '(', Timer(), ')']
        print "Checking all systems for packages with arch 'Unknown'"
        pbar = ProgressBar(widgets=widgets, maxval=len(systemlist), term_width=80).start()
        for box in systemlist:
            count = systemlist.index(box) + 1
            for pkg in system.listPackages(RHN,box['id']):
                if pkg['arch'] == 'Unknown':
                    box['base_channel'] = system.getBaseChannel(RHN, box['id'])
                    failed_systems.append(box)
                    break
            pbar.update(count)
        print 

        if len(failed_systems) > 0:
            print "Systems that require re-registration"
            print "System ID    System Name            Last Checkin Date  Base Software Channel"
            print "----------   --------------------   -----------------  ---------------------"
            pretty_system_list(failed_systems, 'name', reverse=False)

    except KeyboardInterrupt:
        print "operation cancelled"
        sys.exit(1)


    
    
    
