#!/usr/bin/env python
# -*- coding: utf-8 -*-
# RHN/Spacewalk XMLRPC API script
# requires the python-rhnapi module
# and python-progressbar modules
#
#    Copyright 2009-2012 Steven Hardy / Stuart Sears
#
#    This file is part of spw-api-scripts
#
#    spw-api-scripts is free software: you can redistribute it and/or modify it under
#    the terms of the GNU General Public License as published by the Free
#    Software Foundation, either version 2 of the License, or (at your option)
#    any later version.
#
#    spw-api-scripts is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with spw-api-scripts. If not, see http://www.gnu.org/licenses/.

#
# A script to change/list channel org access
#
# Author : Steven Hardy <shardy@redhat.com>
# Based on clone-channel.py

"""
spw_channel_org_access.py

a script to change/list channel org access

This requires the presence of the 'rhnapi' module on your PYTHONPATH.
"""
# ---------------------- Python Standard Libary Modules ---------------------- #
import sys
import os
from optparse import OptionParser, OptionGroup
import logging
import re

# -------------------------- Custom Python Modules --------------------------- #
import rhnapi
from rhnapi import org
from rhnapi import channel
from rhnapi import utils

# --------------------------- Script Configuration --------------------------- #
RHNHOST = 'localhost'
RHNCONFIG = '~/.rhninfo'
# put these in your configfile, dammit;
RHNUSER = None
RHNPASS = None

# ---------------------------------------------------------------------------- #

def parse_cmdline(argv):
    """
    process the commandline :)
    """
    preamble = "Change or list channel org access in your RHN Satellite. "
    usagestr = "%prog [OPTIONS] -c SOURCECHANNEL"
    # intitialise our parser instance and set some core options
    parser = OptionParser(usage = usagestr, description = preamble)
    parser.add_option("-V", "--debug", action = "store_true", default = False,
            help = "enable debug output for RHN session (XMLRPC errors etc")
    parser.add_option("-v", "--verbose", action = "store_true", default = False,
            help = "enable extra informational output")
    parser.add_option("-q", "--quiet", action = "store_true", default = False, help = "Disable all logging and output")

    # RHN Satellite options group
    rhngrp = OptionGroup(parser, "RHN Satellite Options", "Defaults can be set in your RHN API config file (%s)" % RHNCONFIG )
    rhngrp.add_option("--server",help="RHN satellite server hostname [%default]", default=RHNHOST)
    rhngrp.add_option("--login", help="RHN login (username)" , default=RHNUSER)
    rhngrp.add_option("--pass", dest = "password", help="RHN password. This is better off in a config file.", default=RHNPASS)
    rhngrp.add_option("--config", dest = "config", help="Local RHN configuration file [ %default ]", default=RHNCONFIG)
    rhngrp.add_option("-C", "--cache", action = "store_true", default = False,
        help = "save usernames and password in config file, if missing")
    rhngrp.add_option("--log", dest = "logfile", default = None,
        help = "log output to the given filename. If you enable logging without this, logs go to stderr")
    parser.add_option_group(rhngrp)

    changrp = OptionGroup(parser, "Channel Options")
    changrp.add_option("-c","--channel", dest = "channel", help = "channel LABEL", default=None)
    changrp.add_option("-o","--org", dest = "org", help = "org to enable/disable access", default=None)
    changrp.add_option("-l", "--list", help = "list channel org access then exit", action = "store_true", default=False)
    changrp.add_option("-d", "--disable", help = "disable org access", action = "store_true", default=False)
    changrp.add_option("-e", "--enable", help = "enable org access", action = "store_true", default=False)
    parser.add_option_group(changrp)


    opts, args = parser.parse_args()
    if opts.channel is None:
        print "no channel label provided"
        parser.print_help()
        sys.exit(1)

    if opts.disable is False and opts.enable is False and opts.list is False:
        print "must specify enable, disable or list"
        parser.print_help()
        sys.exit(1)

    return opts, args

if __name__ == '__main__':

    # Parse command line args and set loglevel
    opts, args = parse_cmdline(sys.argv)

    try:
        # initialiase an RHN Session with loglevel set to WARNING (30)
        RHN = rhnapi.rhnSession(opts.server, opts.login, opts.password,
                                config=opts.config, savecreds=opts.cache, debug=opts.debug,
                                logfile = opts.logfile, logenable = not(opts.quiet),
                                logname = os.path.basename(sys.argv[0], loglevel=30)
                                )
        # --verbose ?
        # sets logging to INFO level
        if opts.verbose:
            RHN.enableVerbose()

        # did we give the --debug switch?
        # sets logging to DEBUG level
        if opts.debug:
            RHN.enableDebug()

        RHN.logDebug("Got channel %s org %s" % (opts.channel, opts.org))

        # Ensure the requested channel label exists
        channels = [ x['label'] for x in channel.listSoftwareChannels(RHN) ]

        if opts.channel not in channels:
            RHN.logError("source channel %s does not exist. Please try again" % opts.channel)
            RHN.logError("The following channels exist on your satellite:")
            RHN.logError('\n'.join(channels))
            sys.exit(1)

        # If they just asked for --list, we get channel org access and exit
        if opts.list:
            sharing = channel.getOrgSharing(RHN, opts.channel)
            print "Org sharing for channel %s is %s" % (opts.channel, sharing)
            # TODO : If protected then print per-org details
            sys.exit(0)

        # If a specific org was specified, this implies protected access
        if opts.org:
            # Ensure the requested org exists, and get the ID
            org_details = org.getDetails(RHN, opts.org)
            if org_details:
                RHN.logDebug("Found requested org %s, ID is %d", (opts.org, org_details['id']))
            else:
                RHN.logError("Couldn't find org matching name %s!", opts.org)
                RHN.logError("The following orgs exist on your satellite:")
                orgs = org.listOrgs(RHN)
                orgnames = [ x['name'] for x in orgs ]
                print '\n'.join(orgnames)
                sys.exit(1)
            # Set the channel to protected access
            channel.setOrgSharing(RHN, opts.channel, 'protected')
            # Then enable/disable access for the specified org

        # However if they just specify a channel and --enable/--disable
        # this implies public/private access
        else:
            if opts.enable:
                channel.setOrgSharing(RHN, opts.channel, 'public')
            elif opts.disable:
                channel.setOrgSharing(RHN, opts.channel, 'private')
            else:
                RHN.logError("Unexpected error, channel specified with no enable/disable switch!")
                sys.exit(1)
            


    except KeyboardInterrupt:
        print "operation cancelled by keystroke."
        sys.exit(1)

